# MinGW build harness for the Redis Windows port.
#
# This is intentionally separate from the upstream-style POSIX Makefile and the
# legacy Visual Studio project files. It is the first-class build for the
# current WSL/MSYS2 development environment.

BUILD ?= build/mingw64
BUILD_BUNDLED_MODULES ?= no
SKIP_VEC_SETS ?= yes

ifneq ($(BUILD_BUNDLED_MODULES),no)
$(error Bundled Redis modules are outside the initial Windows core-only port)
endif
ifneq ($(SKIP_VEC_SETS),yes)
$(error Vector Sets are temporarily excluded from the Windows core-only bring-up)
endif

JEMALLOC_SRC := deps/jemalloc
JEMALLOC_BUILD := $(BUILD)/jemalloc
JEMALLOC_ABS_SRC := $(abspath $(JEMALLOC_SRC))
WIN32_INTEROP_ABS := $(abspath src/Win32_Interop)

CC := gcc
CXX := g++
AR := ar
RANLIB := ranlib
WINDRES := windres

EVENTLOG_RC := src/Win32_Interop/resources/EventLog.rc
EVENTLOG_MESSAGE := src/Win32_Interop/resources/EventLog_MSG00409.bin
EVENTLOG_OBJ := $(BUILD)/eventlog/EventLog.o
EVENTLOG_DLL := $(BUILD)/EventLog.dll

BASE_DEFS := \
	-DWIN32 \
	-D_WIN32 \
	-DWIN32_LEAN_AND_MEAN \
	-DNOGDI \
	-D__USE_W32_SOCKETS \
	-D_FILE_OFFSET_BITS=64 \
	-D__USE_MINGW_ANSI_STDIO=1 \
	-DLACKS_STDLIB_H \
	-D_CRT_SECURE_NO_WARNINGS \
	-DREDIS_STATIC='' \
	-DPSAPI_VERSION=1 \
	-DENABLE_CJSON_GLOBAL

BASE_INCLUDES := \
	-Ideps/hiredis \
	-Isrc \
	-Ideps/linenoise \
	-Ideps/lua/src \
	-Ideps/hdr_histogram \
	-Ideps/fpconv \
	-Ideps/fast_float \
	-Ideps/xxhash \
	-Ideps/geohash-int \
	-I$(JEMALLOC_BUILD)/include \
	-I$(JEMALLOC_SRC)/include

WARNINGS := \
	-Wall \
	-Wextra \
	-Wno-unknown-pragmas \
	-Wno-unused-parameter

OPT ?= -O2 -g

BASE_CFLAGS := $(OPT) $(WARNINGS) $(BASE_DEFS) $(BASE_INCLUDES)
BASE_CXXFLAGS := $(OPT) $(WARNINGS) $(BASE_DEFS) $(BASE_INCLUDES)

FDAPI_SYSTEM_REDEFS := \
	-Daccept=redis_mingw_system_accept \
	-Daccess=redis_mingw_system_access \
	-Dbind=redis_mingw_system_bind \
	-Dconnect=redis_mingw_system_connect \
	-Dfreeaddrinfo=redis_mingw_system_freeaddrinfo \
	-Dgetaddrinfo=redis_mingw_system_getaddrinfo \
	-Dgetpeername=redis_mingw_system_getpeername \
	-Dgetsockname=redis_mingw_system_getsockname \
	-Dgetsockopt=redis_mingw_system_getsockopt \
	-Dhtonl=redis_mingw_system_htonl \
	-Dhtons=redis_mingw_system_htons \
	-Dinet_ntop=redis_mingw_system_inet_ntop \
	-Dinet_pton=redis_mingw_system_inet_pton \
	-Disatty=redis_mingw_system_isatty \
	-Dlisten=redis_mingw_system_listen \
	-Dlseek64=redis_mingw_system_lseek64 \
	-Dntohl=redis_mingw_system_ntohl \
	-Dntohs=redis_mingw_system_ntohs \
	-Dopen=redis_mingw_system_open \
	-Dread=redis_mingw_system_read \
	-Dselect=redis_mingw_system_select \
	-Dsetsockopt=redis_mingw_system_setsockopt \
	-Dsocket=redis_mingw_system_socket \
	-Dwrite=redis_mingw_system_write \
	-Dgai_strerror=redis_mingw_system_gai_strerror \
	-Dgai_strerrorA=redis_mingw_system_gai_strerrorA \
	-Dgai_strerrorW=redis_mingw_system_gai_strerrorW

SERVER_CFLAGS := $(BASE_CFLAGS) $(FDAPI_SYSTEM_REDEFS) -std=gnu11 -DUSE_JEMALLOC
SERVER_CXXFLAGS := $(BASE_CXXFLAGS) -std=gnu++11 -DUSE_JEMALLOC -DUSE_STATIC
TOOL_CFLAGS := $(BASE_CFLAGS) $(FDAPI_SYSTEM_REDEFS) -std=gnu11 -DNO_QFORKIMPL
TOOL_CXXFLAGS := $(BASE_CXXFLAGS) -std=gnu++11 -DNO_QFORKIMPL
HIREDIS_CFLAGS := $(BASE_CFLAGS) $(FDAPI_SYSTEM_REDEFS) -std=gnu11 -DNO_QFORKIMPL
LUA_CFLAGS := $(BASE_CFLAGS) -std=gnu11 -DNO_QFORKIMPL
HDR_HISTOGRAM_CFLAGS := $(BASE_CFLAGS) -std=gnu11 -DNO_QFORKIMPL -DHDR_MALLOC_INCLUDE=\"hdr_redis_malloc.h\"
FAST_FLOAT_CXXFLAGS := $(SERVER_CXXFLAGS) -DFASTFLOAT_ALLOWS_LEADING_PLUS
XXHASH_CFLAGS := $(BASE_CFLAGS) -std=gnu11 -DNO_QFORKIMPL
TEST_MODULE_CFLAGS := $(OPT) $(WARNINGS) -std=gnu11 -Isrc
TEST_MODULE_LDFLAGS := -shared -static-libgcc -no-pthread -Wl,--export-all-symbols
TEST_MODULE_LDLIBS := -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic
TEST_LAUNCHER_CFLAGS := $(OPT) $(WARNINGS) -std=gnu11
TEST_LAUNCHER_LDFLAGS := -municode -mwindows

LDFLAGS_COMMON := \
	-no-pthread \
	-static-libgcc \
	-static-libstdc++ \
	-Wl,--disable-dynamicbase \
	-Wl,--disable-high-entropy-va

LDLIBS_COMMON := \
	-lws2_32 \
	-lpsapi \
	-ldbghelp \
	-lshlwapi \
	-ladvapi32 \
	-lshell32 \
	-luser32 \
	-lgdi32 \
	-lwinspool

REDIS_HEADERS := $(wildcard src/*.h src/Win32_Interop/*.h deps/geohash-int/*.h deps/hiredis/*.h deps/linenoise/*.h)
HIREDIS_HEADERS := $(wildcard deps/hiredis/*.h)
LUA_HEADERS := $(wildcard deps/lua/src/*.h)
HDR_HISTOGRAM_HEADERS := $(wildcard deps/hdr_histogram/*.h)
FPCONV_HEADERS := $(wildcard deps/fpconv/*.h)
FAST_FLOAT_HEADERS := $(wildcard deps/fast_float/*.h)
XXHASH_HEADERS := $(wildcard deps/xxhash/*.h)

SERVER_C_SOURCES := \
	src/threads_mngr.c \
	src/acl.c \
	src/adlist.c \
	src/ae.c \
	src/anet.c \
	src/aof.c \
	src/bio.c \
	src/bitops.c \
	src/blocked.c \
	src/childinfo.c \
	src/chk.c \
	src/cluster.c \
	src/cluster_asm.c \
	src/cluster_legacy.c \
	src/cluster_slot_stats.c \
	src/config.c \
	src/connection.c \
	src/crc16.c \
	src/crc64.c \
	src/crccombine.c \
	src/crcspeed.c \
	src/db.c \
	src/debug.c \
	src/defrag.c \
	src/dict.c \
	src/ebuckets.c \
	src/endianconv.c \
	src/entry.c \
	src/estore.c \
	src/evict.c \
	src/expire.c \
	src/eventnotifier.c \
	src/geo.c \
	src/geohash.c \
	src/geohash_helper.c \
	src/hyperloglog.c \
	src/hotkeys.c \
	src/intset.c \
	src/iothread.c \
	src/keymeta.c \
	src/kvstore.c \
	src/latency.c \
	src/lazyfree.c \
	src/listpack.c \
	src/lolwut.c \
	src/lolwut5.c \
	src/lolwut6.c \
	src/lolwut8.c \
	src/lzf_c.c \
	src/lzf_d.c \
	src/memory_prefetch.c \
	src/memtest.c \
	src/module.c \
	src/monotonic.c \
	src/mstr.c \
	src/mt19937-64.c \
	src/multi.c \
	src/networking.c \
	src/notify.c \
	src/object.c \
	src/pqsort.c \
	src/pubsub.c \
	src/quicklist.c \
	src/rand.c \
	src/rax.c \
	src/rdb.c \
	src/redis-check-aof.c \
	src/redis-check-rdb.c \
	src/release.c \
	src/replication.c \
	src/rio.c \
	src/eval.c \
	src/call_reply.c \
	src/commands.c \
	src/functions.c \
	src/function_lua.c \
	src/fwtree.c \
	src/script.c \
	src/script_lua.c \
	src/resp_parser.c \
	src/socket.c \
	src/unix.c \
	src/logreqres.c \
	src/localtime.c \
	src/strl.c \
	src/sds.c \
	src/sentinel.c \
	src/server.c \
	src/setcpuaffinity.c \
	src/setproctitle.c \
	src/sha1.c \
	src/sha256.c \
	src/siphash.c \
	src/slowlog.c \
	src/sort.c \
	src/sparkline.c \
	src/syncio.c \
	src/syscheck.c \
	src/t_hash.c \
	src/t_list.c \
	src/t_set.c \
	src/t_stream.c \
	src/t_string.c \
	src/t_zset.c \
	src/timeout.c \
	src/tls.c \
	src/tracking.c \
	src/util.c \
	src/ziplist.c \
	src/zipmap.c \
	src/zmalloc.c

WIN32_INTEROP_C_SOURCES := \
	src/Win32_Interop/win32fixes.c \
	src/Win32_Interop/Win32_ANSI.c \
	src/Win32_Interop/Win32_APIs.c \
	src/Win32_Interop/Win32_Error.c \
	src/Win32_Interop/Win32_PThread.c \
	src/Win32_Interop/Win32_QFork_impl.c \
	src/Win32_Interop/Win32_RedisLog.c \
	src/Win32_Interop/Win32_Signal_Process.c \
	src/Win32_Interop/Win32_ThreadControl.c \
	src/Win32_Interop/Win32_Time.c \
	src/Win32_Interop/win32_wsiocp.c \
	src/Win32_Interop/dlfcn.c

WIN32_INTEROP_CXX_SOURCES := \
	src/Win32_Interop/Win32_CommandLine.cpp \
	src/Win32_Interop/Win32_Common.cpp \
	src/Win32_Interop/Win32_EventLog.cpp \
	src/Win32_Interop/Win32_FDAPI.cpp \
	src/Win32_Interop/Win32_fdapi_crt.cpp \
	src/Win32_Interop/Win32_QFork.cpp \
	src/Win32_Interop/win32_rfdmap.cpp \
	src/Win32_Interop/Win32_service.cpp \
	src/Win32_Interop/Win32_StackTrace.cpp \
	src/Win32_Interop/Win32_variadicFunctor.cpp

TOOL_WIN32_INTEROP_C_SOURCES := \
	src/Win32_Interop/win32fixes.c \
	src/Win32_Interop/Win32_ANSI.c \
	src/Win32_Interop/Win32_APIs.c \
	src/Win32_Interop/Win32_Error.c \
	src/Win32_Interop/Win32_PThread.c \
	src/Win32_Interop/Win32_RedisLog.c \
	src/Win32_Interop/Win32_Signal_Process.c \
	src/Win32_Interop/Win32_ThreadControl.c \
	src/Win32_Interop/Win32_Time.c \
	src/Win32_Interop/win32_wsiocp.c

TOOL_WIN32_INTEROP_CXX_SOURCES := \
	src/Win32_Interop/Win32_CommandLine.cpp \
	src/Win32_Interop/Win32_Common.cpp \
	src/Win32_Interop/Win32_EventLog.cpp \
	src/Win32_Interop/Win32_FDAPI.cpp \
	src/Win32_Interop/Win32_fdapi_crt.cpp \
	src/Win32_Interop/win32_rfdmap.cpp \
	src/Win32_Interop/Win32_service.cpp \
	src/Win32_Interop/Win32_variadicFunctor.cpp

HIREDIS_SOURCES := \
	deps/hiredis/alloc.c \
	deps/hiredis/async.c \
	deps/hiredis/hiredis.c \
	deps/hiredis/net.c \
	deps/hiredis/read.c \
	deps/hiredis/sds.c

HDR_HISTOGRAM_SOURCES := \
	deps/hdr_histogram/hdr_histogram.c

FPCONV_SOURCES := \
	deps/fpconv/fpconv_dtoa.c

FAST_FLOAT_CXX_SOURCES := \
	deps/fast_float/fast_float_strtod.cpp

XXHASH_SOURCES := \
	deps/xxhash/xxhash.c

LUA_SOURCES := \
	deps/lua/src/fpconv.c \
	deps/lua/src/lapi.c \
	deps/lua/src/lauxlib.c \
	deps/lua/src/lbaselib.c \
	deps/lua/src/lcode.c \
	deps/lua/src/ldblib.c \
	deps/lua/src/ldebug.c \
	deps/lua/src/ldo.c \
	deps/lua/src/ldump.c \
	deps/lua/src/lfunc.c \
	deps/lua/src/lgc.c \
	deps/lua/src/linit.c \
	deps/lua/src/liolib.c \
	deps/lua/src/llex.c \
	deps/lua/src/lmathlib.c \
	deps/lua/src/lmem.c \
	deps/lua/src/loadlib.c \
	deps/lua/src/lobject.c \
	deps/lua/src/lopcodes.c \
	deps/lua/src/loslib.c \
	deps/lua/src/lparser.c \
	deps/lua/src/lstate.c \
	deps/lua/src/lstring.c \
	deps/lua/src/lstrlib.c \
	deps/lua/src/ltable.c \
	deps/lua/src/ltablib.c \
	deps/lua/src/ltm.c \
	deps/lua/src/lua_bit.c \
	deps/lua/src/lua_cjson.c \
	deps/lua/src/lua_cmsgpack.c \
	deps/lua/src/lua_struct.c \
	deps/lua/src/lundump.c \
	deps/lua/src/lvm.c \
	deps/lua/src/lzio.c \
	deps/lua/src/strbuf.c

SERVER_OBJS := \
	$(addprefix $(BUILD)/server/,$(SERVER_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/server/,$(WIN32_INTEROP_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/server/,$(WIN32_INTEROP_CXX_SOURCES:.cpp=.o)) \
	$(EVENTLOG_OBJ)

HIREDIS_OBJS := $(addprefix $(BUILD)/hiredis/,$(HIREDIS_SOURCES:.c=.o))
LUA_OBJS := $(addprefix $(BUILD)/lua/,$(LUA_SOURCES:.c=.o))
HDR_HISTOGRAM_OBJS := $(addprefix $(BUILD)/hdr_histogram/,$(HDR_HISTOGRAM_SOURCES:.c=.o))
FPCONV_OBJS := $(addprefix $(BUILD)/fpconv/,$(FPCONV_SOURCES:.c=.o))
FAST_FLOAT_OBJS := $(addprefix $(BUILD)/fast_float/,$(FAST_FLOAT_CXX_SOURCES:.cpp=.o))
XXHASH_OBJS := $(addprefix $(BUILD)/xxhash/,$(XXHASH_SOURCES:.c=.o))
HIREDIS_TEST_OBJS := \
	$(BUILD)/hiredis-test/deps/hiredis/test.o \
	$(BUILD)/hiredis-test/src/adlist.o \
	$(BUILD)/hiredis-test/src/ae.o \
	$(BUILD)/hiredis-test/src/monotonic.o \
	$(BUILD)/hiredis-test/src/zmalloc.o \
	$(addprefix $(BUILD)/hiredis-test/,$(TOOL_WIN32_INTEROP_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/hiredis-test/,$(TOOL_WIN32_INTEROP_CXX_SOURCES:.cpp=.o))

INTEROP_TEST_C_SOURCES := \
	src/Win32_Interop/Win32_Error.c \
	src/Win32_Interop/Win32_PThread.c \
	src/Win32_Interop/Win32_Signal_Process.c \
	src/Win32_Interop/Win32_ThreadControl.c

INTEROP_TEST_CXX_SOURCES := \
	tests/windows/interop.cpp \
	src/Win32_Interop/Win32_FDAPI.cpp \
	src/Win32_Interop/Win32_fdapi_crt.cpp \
	src/Win32_Interop/win32_rfdmap.cpp \
	src/Win32_Interop/Win32_variadicFunctor.cpp

INTEROP_TEST_OBJS := \
	$(addprefix $(BUILD)/interop-test/,$(INTEROP_TEST_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/interop-test/,$(INTEROP_TEST_CXX_SOURCES:.cpp=.o))

CLI_SOURCES := \
	deps/linenoise/linenoise.c \
	src/adlist.c \
	src/ae.c \
	src/anet.c \
	src/cli_common.c \
	src/cli_commands.c \
	src/crc16.c \
	src/crc64.c \
	src/crccombine.c \
	src/crcspeed.c \
	src/dict.c \
	src/monotonic.c \
	src/mt19937-64.c \
	src/redis-cli.c \
	src/redisassert.c \
	src/release.c \
	src/siphash.c \
	src/strl.c \
	src/zmalloc.c

BENCHMARK_SOURCES := \
	src/adlist.c \
	src/ae.c \
	src/anet.c \
	src/cli_common.c \
	src/crc16.c \
	src/crc64.c \
	src/crccombine.c \
	src/crcspeed.c \
	src/dict.c \
	src/monotonic.c \
	src/mt19937-64.c \
	src/redis-benchmark.c \
	src/redisassert.c \
	src/release.c \
	src/siphash.c \
	src/strl.c \
	src/zmalloc.c

CLI_OBJS := \
	$(addprefix $(BUILD)/cli/,$(CLI_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/cli/,$(TOOL_WIN32_INTEROP_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/cli/,$(TOOL_WIN32_INTEROP_CXX_SOURCES:.cpp=.o))

BENCHMARK_OBJS := \
	$(addprefix $(BUILD)/benchmark/,$(BENCHMARK_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/benchmark/,$(TOOL_WIN32_INTEROP_C_SOURCES:.c=.o)) \
	$(addprefix $(BUILD)/benchmark/,$(TOOL_WIN32_INTEROP_CXX_SOURCES:.cpp=.o))

AE_BACKEND_SOURCE := src/ae_wsiocp.c
AE_OBJS := \
	$(BUILD)/server/src/ae.o \
	$(BUILD)/cli/src/ae.o \
	$(BUILD)/benchmark/src/ae.o \
	$(BUILD)/hiredis-test/src/ae.o

HIREDIS_LIB := $(BUILD)/lib/libhiredis.a
LUA_LIB := $(BUILD)/lib/liblua.a
JEMALLOC_LIB := $(JEMALLOC_BUILD)/lib/jemalloc.lib
FPCONV_LIB := $(BUILD)/lib/libfpconv.a
FAST_FLOAT_LIB := $(BUILD)/lib/libfast_float.a
XXHASH_LIB := $(BUILD)/lib/libxxhash.a
REDIS_CHECK_ALIASES := $(BUILD)/redis-check-aof.exe $(BUILD)/redis-check-rdb.exe
TEST_MODULE_SOURCES := $(sort $(wildcard tests/modules/*.c))
TEST_MODULES := $(patsubst tests/modules/%.c,$(BUILD)/tests/modules/%.so,$(TEST_MODULE_SOURCES))

.PHONY: all clean distclean deps eventlog hiredis-test interop-test test-launcher test-modules FORCE

all: $(BUILD)/redis-server.exe $(BUILD)/redis-cli.exe $(BUILD)/redis-benchmark.exe $(REDIS_CHECK_ALIASES) $(EVENTLOG_DLL) $(BUILD)/redis-test-launcher.exe $(TEST_MODULES)

deps: $(HIREDIS_LIB) $(LUA_LIB) $(HDR_HISTOGRAM_OBJS) $(FPCONV_LIB) $(FAST_FLOAT_LIB) $(XXHASH_LIB) $(JEMALLOC_LIB)

eventlog: $(EVENTLOG_DLL)

hiredis-test: $(BUILD)/hiredis-test.exe

interop-test: $(BUILD)/interop-test.exe

test-launcher: $(BUILD)/redis-test-launcher.exe

test-modules: $(TEST_MODULES)

src/release.h: FORCE
	cd src && ./mkreleasehdr.sh

# The generated header is ignored and can outlive a branch switch or a
# linked-worktree checkout. Always let mkreleasehdr.sh verify its commit and
# dirty-tree metadata; it only rewrites the file (and touches release.c) when
# those values actually changed.
FORCE:

$(JEMALLOC_SRC)/configure: $(JEMALLOC_SRC)/configure.ac
	cd $(JEMALLOC_SRC) && autoconf

$(JEMALLOC_BUILD)/Makefile: $(JEMALLOC_SRC)/configure Makefile.mingw
	mkdir -p $(JEMALLOC_BUILD)
	cd $(JEMALLOC_BUILD) && $(JEMALLOC_ABS_SRC)/configure \
		--disable-shared \
		--enable-static \
		--with-version=5.3.0-0-g0000000000000000000000000000000000000000 \
		--with-malloc-conf=retain:false,slab_sizes:1-16777216:1 \
		--with-jemalloc-prefix=je_ \
		--with-lg-quantum=3 \
		--with-lg-page=22 \
		--with-lg-hugepage=22 \
		CFLAGS="$(OPT) -DUSE_WIN32_EXTERNAL_HEAP_ALLOC -I$(WIN32_INTEROP_ABS)" \
		LIBS="-lm"

$(JEMALLOC_LIB): $(JEMALLOC_BUILD)/Makefile
	$(MAKE) -C $(JEMALLOC_BUILD) lib/jemalloc.lib

$(FPCONV_LIB): $(FPCONV_OBJS)
	mkdir -p $(dir $@)
	$(AR) rcs $@ $^
	$(RANLIB) $@

$(FAST_FLOAT_LIB): $(FAST_FLOAT_OBJS)
	mkdir -p $(dir $@)
	$(AR) rcs $@ $^
	$(RANLIB) $@

$(XXHASH_LIB): $(XXHASH_OBJS)
	mkdir -p $(dir $@)
	$(AR) rcs $@ $^
	$(RANLIB) $@

$(HIREDIS_LIB): Makefile.mingw $(HIREDIS_OBJS)
	mkdir -p $(dir $@)
	rm -f $@
	$(AR) rcs $@ $(HIREDIS_OBJS)
	$(RANLIB) $@

$(LUA_LIB): $(LUA_OBJS)
	mkdir -p $(dir $@)
	$(AR) rcs $@ $^
	$(RANLIB) $@

$(EVENTLOG_OBJ): $(EVENTLOG_RC) $(EVENTLOG_MESSAGE) Makefile.mingw
	mkdir -p $(dir $@)
	$(WINDRES) -I $(dir $(EVENTLOG_RC)) -i $(EVENTLOG_RC) -o $@ -O coff

$(EVENTLOG_DLL): Makefile.mingw $(EVENTLOG_OBJ)
	$(CC) -shared -nostdlib -Wl,--entry,0 -o $@ $(EVENTLOG_OBJ)

$(BUILD)/redis-server.exe: Makefile.mingw $(SERVER_OBJS) $(HIREDIS_LIB) $(LUA_LIB) $(HDR_HISTOGRAM_OBJS) $(JEMALLOC_LIB) $(FPCONV_LIB) $(FAST_FLOAT_LIB) $(XXHASH_LIB)
	$(CXX) $(LDFLAGS_COMMON) -o $@ $(SERVER_OBJS) $(HIREDIS_LIB) $(LUA_LIB) $(HDR_HISTOGRAM_OBJS) $(JEMALLOC_LIB) $(FPCONV_LIB) $(FAST_FLOAT_LIB) $(XXHASH_LIB) $(LDLIBS_COMMON)

$(BUILD)/redis-cli.exe: Makefile.mingw $(CLI_OBJS) $(HIREDIS_LIB) $(HDR_HISTOGRAM_OBJS)
	$(CXX) $(LDFLAGS_COMMON) -o $@ $(CLI_OBJS) $(HIREDIS_LIB) $(HDR_HISTOGRAM_OBJS) $(LDLIBS_COMMON)

$(BUILD)/redis-benchmark.exe: Makefile.mingw $(BENCHMARK_OBJS) $(HIREDIS_LIB) $(HDR_HISTOGRAM_OBJS) $(FPCONV_LIB)
	$(CXX) $(LDFLAGS_COMMON) -o $@ $(BENCHMARK_OBJS) $(HIREDIS_LIB) $(HDR_HISTOGRAM_OBJS) $(FPCONV_LIB) $(LDLIBS_COMMON)

$(REDIS_CHECK_ALIASES): $(BUILD)/redis-server.exe
	cp -f $< $@

$(BUILD)/hiredis-test.exe: Makefile.mingw $(HIREDIS_TEST_OBJS) $(HIREDIS_LIB)
	$(CXX) $(LDFLAGS_COMMON) -o $@ $(HIREDIS_TEST_OBJS) $(HIREDIS_LIB) $(LDLIBS_COMMON)

$(BUILD)/interop-test.exe: Makefile.mingw $(INTEROP_TEST_OBJS)
	$(CXX) $(LDFLAGS_COMMON) -o $@ $(INTEROP_TEST_OBJS) $(LDLIBS_COMMON)

$(AE_OBJS): $(AE_BACKEND_SOURCE)

$(BUILD)/redis-test-launcher.exe: Makefile.mingw tests/windows/test-launcher.c
	mkdir -p $(dir $@)
	$(CC) $(TEST_LAUNCHER_CFLAGS) $(TEST_LAUNCHER_LDFLAGS) $(LDFLAGS_COMMON) -o $@ tests/windows/test-launcher.c -lws2_32

$(BUILD)/tests/modules/%.so: tests/modules/%.c src/redismodule.h src/Win32_Interop/win32_types_hiredis.h Makefile.mingw
	mkdir -p $(dir $@)
	$(CC) $(TEST_MODULE_CFLAGS) $(TEST_MODULE_LDFLAGS) -o $@ $< $(TEST_MODULE_LDLIBS)

$(BUILD)/server/%.o: %.c src/release.h $(REDIS_HEADERS) $(JEMALLOC_LIB)
	mkdir -p $(dir $@)
	$(CC) $(SERVER_CFLAGS) -c $< -o $@

$(BUILD)/server/%.o: %.cpp $(REDIS_HEADERS) $(JEMALLOC_LIB)
	mkdir -p $(dir $@)
	$(CXX) $(SERVER_CXXFLAGS) -c $< -o $@

$(BUILD)/hiredis/%.o: %.c $(HIREDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(HIREDIS_CFLAGS) -c $< -o $@

$(BUILD)/lua/%.o: %.c $(LUA_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(LUA_CFLAGS) -DLUA_ANSI -c $< -o $@

$(BUILD)/hdr_histogram/%.o: %.c $(HDR_HISTOGRAM_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(HDR_HISTOGRAM_CFLAGS) -c $< -o $@

$(BUILD)/fpconv/%.o: %.c $(FPCONV_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(BASE_CFLAGS) -std=gnu11 -DNO_QFORKIMPL -c $< -o $@

$(BUILD)/fast_float/%.o: %.cpp $(FAST_FLOAT_HEADERS)
	mkdir -p $(dir $@)
	$(CXX) $(FAST_FLOAT_CXXFLAGS) -c $< -o $@

$(BUILD)/xxhash/%.o: %.c $(XXHASH_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(XXHASH_CFLAGS) -c $< -o $@

$(BUILD)/cli/%.o: %.c src/release.h $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(TOOL_CFLAGS) -c $< -o $@

$(BUILD)/cli/%.o: %.cpp $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CXX) $(TOOL_CXXFLAGS) -c $< -o $@

$(BUILD)/benchmark/%.o: %.c src/release.h $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(TOOL_CFLAGS) -c $< -o $@

$(BUILD)/benchmark/%.o: %.cpp $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CXX) $(TOOL_CXXFLAGS) -c $< -o $@

$(BUILD)/hiredis-test/%.o: %.c src/release.h $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(TOOL_CFLAGS) -c $< -o $@

$(BUILD)/hiredis-test/%.o: %.cpp $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CXX) $(TOOL_CXXFLAGS) -c $< -o $@

$(BUILD)/interop-test/%.o: %.c src/release.h $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CC) $(TOOL_CFLAGS) -c $< -o $@

$(BUILD)/interop-test/%.o: %.cpp $(REDIS_HEADERS)
	mkdir -p $(dir $@)
	$(CXX) $(TOOL_CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD)/server $(BUILD)/hiredis $(BUILD)/lua $(BUILD)/hdr_histogram $(BUILD)/fpconv $(BUILD)/fast_float $(BUILD)/xxhash $(BUILD)/cli $(BUILD)/benchmark
	rm -rf $(BUILD)/eventlog $(BUILD)/hiredis-test $(BUILD)/interop-test
	rm -rf $(BUILD)/tests/modules
	rm -f $(BUILD)/redis-server.exe $(BUILD)/redis-cli.exe $(BUILD)/redis-benchmark.exe $(REDIS_CHECK_ALIASES) $(EVENTLOG_DLL) $(BUILD)/hiredis-test.exe $(BUILD)/interop-test.exe $(BUILD)/redis-test-launcher.exe
	rm -rf $(BUILD)/lib

distclean: clean
	rm -rf $(JEMALLOC_BUILD)
